language: python
python:
- 3.6
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
- pip install -e .
script:
- pytest
env:
  global:
  - secure: askFJXE0Ipfz2kacrnR2Jb5FSj1QSKlGBas0bMayjryOOoGbX7B4qUfo4yus4t2W5LOmWrWejkHd7dR/z8Umr7Q3V4pLYNOxVNR7+hqwtlDhsCoxMfxfU4RPmn9CQ9ZSNAbLLuaKYqYaUPsVBY5gdcIfe5edwQuZqnwPd1zo+IlCjAWvBARPKKu5zGxMKIN6PimicHz3IeDGWFDGvAMlRk2kZjSmL72hSmnOE4ysb2gtA/CRGFnbW9Ao09TTeJtZJ825p1R1MSB0o5ktQoXHln3XcbaEQOFIoWugh1RMpbJxtAozCkfBAcVyRsTH+VUM2lzdOy6xFIHi7+/uaT9F2kfPcffCpC/1B7GJmgVrdDuW9O+7CgoAr7MbH08moP/tTfcywxYWbkCLqXNFZpxeU1KTuqW0aG62+tbe5GCEi0AnmlJ3f0p1We/Ef8fPA+TYTPR0gth9FnnD10KNcaOKx7QXLEjczSkCNiQ5IlmPC7Gou/kwGf/GD5oZCz2BqgALdTs+PqLyAnV5QeduXl3amgX2ATJTDFskytF8chN1bldo9fGKC1WUOU7ICrWJK7bwywBZfftHbONGsgkhp7UvtyHcOH8Rrj62SjCtCOnDRs2VF5YDvS28w52E+bWRP1UHpRA9gCf+tyNCPBA74CBj9aGE+A8+0++pU41ny4J7a3M=
  - secure: HU8j4oFWR+FEfjz7syhUH8NYF0v6+Qbm+EtCPyyPpqk7qEWSSOezve4FDFQpAHjzOXA03bqLLJJ7sRU8845fda8gDesZvGJ8j0YgqGz/nudTeKXT+6GKZEuk589xAV01lcWacocPNiteFWWqwdBnDer2kwC6xNILNRJa+aOvDC7re4OVrOy+ZuICazb/EA9SIgaCSqYWqZIVcfaIuSmL3JFjdNQXRGYEqIa0yAN37u63JQsWplxZ0lxbBjqEAVqSE6/6S305Mlhv0XFyPL3bRGwGnm1gv9cmmbgpl3weHIxRa5uCaGK9++TUQqo+k+mSTjR912jUHdqdFAKJoiHfXsJ/SG0aFxe1jMTffHORdXYVeW4icRbWFcA5eD7EaFHiwuUBx/JuCQmGCEBymTTdh3NGCvXj/qFIUH6magWID3K3QYuTlouiEsj/YPTZY210YrDXAnfV/0NmwB6YGv5jMXEeFvJz5mxUiGrsut3+rk26N4dHObPZLJ6bBb2r+JknzmjN0Oigd7ly8/HC+47zHqEeg17cBc4UNS5VeQ1dC0CK+dvNcTcZryhGgFwB3YRuORsNb6lx/y38PPH8aH0KcKC9wsMwvEHqptAhjM7HZ00d1Bfc4Tn3qR/uPuN41H3dQfAeYvODym7j/1ICQqU0nxYso3vx0awLJQ3ybg6aTH0=
